/* The following code was generated by JFlex 1.4.3 on 19/06/17 21:55 */

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 19/06/17 21:55 from the specification file
 * <tt>lexicoT1.flex</tt>
 */
class Yylex {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\51\1\1\2\0\1\1\22\0\1\51\1\45\2\0\1\2"+
    "\1\0\1\44\1\0\1\45\1\45\1\45\1\45\1\45\1\45\1\43"+
    "\1\46\12\50\1\0\1\45\1\45\1\45\1\45\2\0\1\5\1\47"+
    "\1\6\1\47\1\7\1\13\7\47\1\12\1\11\2\47\1\4\1\32"+
    "\1\3\6\47\1\45\1\0\1\45\1\0\1\10\1\0\1\16\1\22"+
    "\1\14\1\27\1\35\1\37\1\34\1\41\1\23\2\47\1\15\1\30"+
    "\1\31\1\26\1\20\1\47\1\33\1\17\1\24\1\21\1\25\1\40"+
    "\1\36\1\42\1\47\1\45\1\0\1\45\uff82\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\1\20\3\1\4\1\1\1\4"+
    "\1\5\1\6\1\0\6\3\1\7\14\3\1\10\1\6"+
    "\1\0\5\3\1\11\4\3\1\12\7\3\1\0\5\3"+
    "\1\13\1\14\1\15\1\16\3\3\1\17\3\3\1\0"+
    "\1\20\10\3\1\21\1\22\1\0\1\23\1\24\1\25"+
    "\1\3\1\26\1\3\1\27\1\3\1\0\1\30\1\0"+
    "\1\31\2\0\1\32\2\0\1\33\10\0\1\34";

  private static int [] zzUnpackAction() {
    int [] result = new int[123];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\52\0\124\0\176\0\250\0\322\0\374\0\u0126"+
    "\0\u0150\0\u017a\0\u01a4\0\u01ce\0\u01f8\0\u0222\0\u024c\0\u0276"+
    "\0\u02a0\0\u02ca\0\u02f4\0\u031e\0\52\0\u0348\0\u0372\0\u039c"+
    "\0\u03c6\0\u03f0\0\u041a\0\u0444\0\u046e\0\u0498\0\u04c2\0\u04ec"+
    "\0\250\0\u0516\0\u0540\0\u056a\0\u0594\0\u05be\0\u05e8\0\u0612"+
    "\0\u063c\0\u0666\0\u0690\0\u06ba\0\u06e4\0\52\0\u070e\0\u0738"+
    "\0\u0762\0\u078c\0\u07b6\0\u07e0\0\u080a\0\250\0\u0834\0\u085e"+
    "\0\u0888\0\u08b2\0\250\0\u08dc\0\u0906\0\u0930\0\u095a\0\u0984"+
    "\0\u09ae\0\u09d8\0\u0a02\0\u0a2c\0\u0a56\0\u0a80\0\u0aaa\0\u0ad4"+
    "\0\250\0\250\0\250\0\250\0\u0afe\0\u0b28\0\u0b52\0\250"+
    "\0\u0b7c\0\u0ba6\0\u0bd0\0\u0bfa\0\250\0\u0c24\0\u0c4e\0\u0c78"+
    "\0\u0ca2\0\u0ccc\0\u0cf6\0\u0d20\0\u0d4a\0\250\0\250\0\u0d74"+
    "\0\250\0\250\0\250\0\u0d9e\0\250\0\u0dc8\0\250\0\u0df2"+
    "\0\u0e1c\0\250\0\u0e46\0\250\0\u0e70\0\u0e9a\0\52\0\u0ec4"+
    "\0\u0eee\0\52\0\u0f18\0\u0f42\0\u0f6c\0\u0f96\0\u0fc0\0\u0fea"+
    "\0\u1014\0\u103e\0\52";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[123];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\5\5\1\2\3\5\1\6\1\7"+
    "\1\5\1\10\1\11\1\5\1\12\1\13\1\14\1\15"+
    "\2\5\1\16\1\17\1\20\1\21\1\5\1\22\1\5"+
    "\1\23\1\24\2\5\1\25\1\26\1\25\1\27\1\5"+
    "\1\30\1\31\53\0\1\3\53\0\1\32\51\0\40\5"+
    "\4\0\2\5\4\0\12\5\1\33\25\5\4\0\2\5"+
    "\4\0\32\5\1\34\5\5\4\0\2\5\4\0\21\5"+
    "\1\35\16\5\4\0\2\5\4\0\16\5\1\36\21\5"+
    "\4\0\2\5\4\0\23\5\1\37\14\5\4\0\2\5"+
    "\4\0\26\5\1\40\5\5\1\41\3\5\4\0\2\5"+
    "\4\0\30\5\1\42\5\5\1\43\1\5\4\0\2\5"+
    "\4\0\23\5\1\44\14\5\4\0\2\5\4\0\13\5"+
    "\1\45\24\5\4\0\2\5\4\0\32\5\1\46\5\5"+
    "\4\0\2\5\4\0\21\5\1\47\15\5\1\50\4\0"+
    "\2\5\4\0\32\5\1\51\5\5\4\0\2\5\4\0"+
    "\12\5\1\52\20\5\1\53\4\5\4\0\2\5\4\0"+
    "\13\5\1\54\24\5\4\0\2\5\4\0\36\5\1\55"+
    "\1\5\4\0\2\5\45\0\1\56\53\0\1\57\53\0"+
    "\1\30\52\0\1\31\4\0\1\60\50\0\13\5\1\61"+
    "\24\5\4\0\2\5\4\0\26\5\1\62\11\5\4\0"+
    "\2\5\4\0\13\5\1\63\24\5\4\0\2\5\4\0"+
    "\17\5\1\64\20\5\4\0\2\5\4\0\23\5\1\65"+
    "\14\5\4\0\2\5\4\0\21\5\1\66\16\5\4\0"+
    "\2\5\4\0\16\5\1\67\21\5\4\0\2\5\4\0"+
    "\20\5\1\70\17\5\4\0\2\5\4\0\20\5\1\71"+
    "\17\5\4\0\2\5\4\0\20\5\1\72\17\5\4\0"+
    "\2\5\4\0\35\5\1\73\2\5\4\0\2\5\4\0"+
    "\30\5\1\74\7\5\4\0\2\5\4\0\14\5\1\75"+
    "\23\5\4\0\2\5\4\0\21\5\1\76\16\5\4\0"+
    "\2\5\4\0\14\5\1\77\23\5\4\0\2\5\4\0"+
    "\21\5\1\100\16\5\4\0\2\5\4\0\12\5\1\101"+
    "\25\5\4\0\2\5\4\0\20\5\1\102\17\5\4\0"+
    "\2\5\1\0\1\57\1\0\50\57\5\0\1\103\47\0"+
    "\14\5\1\104\23\5\4\0\2\5\4\0\31\5\1\105"+
    "\6\5\4\0\2\5\4\0\21\5\1\106\16\5\4\0"+
    "\2\5\4\0\12\5\1\107\25\5\4\0\2\5\4\0"+
    "\12\5\1\110\25\5\4\0\2\5\4\0\32\5\1\111"+
    "\5\5\4\0\2\5\4\0\14\5\1\112\23\5\4\0"+
    "\2\5\4\0\24\5\1\113\13\5\4\0\2\5\4\0"+
    "\26\5\1\114\11\5\4\0\2\5\4\0\20\5\1\115"+
    "\17\5\4\0\2\5\4\0\21\5\1\116\16\5\4\0"+
    "\2\5\4\0\16\5\1\117\21\5\4\0\2\5\4\0"+
    "\32\5\1\120\5\5\4\0\2\5\4\0\32\5\1\121"+
    "\5\5\4\0\2\5\4\0\14\5\1\122\23\5\4\0"+
    "\2\5\4\0\12\5\1\123\25\5\4\0\2\5\7\0"+
    "\1\124\46\0\14\5\1\125\23\5\4\0\2\5\4\0"+
    "\21\5\1\126\16\5\4\0\2\5\4\0\20\5\1\127"+
    "\17\5\4\0\2\5\4\0\20\5\1\130\17\5\4\0"+
    "\2\5\4\0\32\5\1\131\5\5\4\0\2\5\4\0"+
    "\26\5\1\132\11\5\4\0\2\5\4\0\32\5\1\133"+
    "\5\5\4\0\2\5\4\0\30\5\1\134\7\5\4\0"+
    "\2\5\4\0\26\5\1\135\11\5\4\0\2\5\4\0"+
    "\32\5\1\136\5\5\4\0\2\5\4\0\32\5\1\137"+
    "\5\5\4\0\2\5\10\0\1\140\45\0\36\5\1\141"+
    "\1\5\4\0\2\5\4\0\11\5\1\142\26\5\4\0"+
    "\2\5\4\0\11\5\1\143\26\5\4\0\2\5\4\0"+
    "\13\5\1\144\24\5\4\0\2\5\4\0\31\5\1\145"+
    "\6\5\4\0\2\5\4\0\25\5\1\146\12\5\4\0"+
    "\2\5\4\0\26\5\1\147\11\5\4\0\2\5\4\0"+
    "\24\5\1\150\13\5\4\0\2\5\11\0\1\151\44\0"+
    "\26\5\1\152\11\5\4\0\2\5\4\0\40\5\1\153"+
    "\3\0\2\5\4\0\14\5\1\154\23\5\4\0\2\5"+
    "\12\0\1\155\66\0\1\156\35\0\1\157\1\160\57\0"+
    "\1\161\43\0\1\162\62\0\1\163\70\0\1\164\26\0"+
    "\1\165\64\0\1\166\41\0\1\167\57\0\1\170\44\0"+
    "\1\171\42\0\1\172\65\0\1\173\20\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[4200];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\22\1\1\11\4\1\1\0\23\1\1\11"+
    "\1\1\1\0\22\1\1\0\20\1\1\0\13\1\1\0"+
    "\10\1\1\0\1\1\1\0\1\1\2\0\1\11\2\0"+
    "\1\11\10\0\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[123];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
  private Parser yyparser;

  public Yylex(java.io.Reader r, Parser yyparser) {
    this(r);
    this.yyparser = yyparser;
  }

  public int getLine() { return yyline; }



  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Yylex(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  Yylex(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 154) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public int yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 22: 
          { return Parser.STRING;
          }
        case 29: break;
        case 7: 
          { return Parser.IF;
          }
        case 30: break;
        case 20: 
          { return Parser.STATIC;
          }
        case 31: break;
        case 2: 
          { yyline++;
          }
        case 32: break;
        case 26: 
          { yyparser.setDebug(true);
          }
        case 33: break;
        case 16: 
          { return Parser.CLASS;
          }
        case 34: break;
        case 24: 
          { return Parser.BOOL;
          }
        case 35: break;
        case 25: 
          { return Parser.EXTENDS;
          }
        case 36: break;
        case 14: 
          { return Parser.MAIN;
          }
        case 37: break;
        case 8: 
          { return Parser.AND;
          }
        case 38: break;
        case 4: 
          { return (int) yycharat(0);
          }
        case 39: break;
        case 28: 
          { return Parser.PRINT;
          }
        case 40: break;
        case 27: 
          { yyparser.setDebug(false);
          }
        case 41: break;
        case 21: 
          { return Parser.PUBLIC;
          }
        case 42: break;
        case 12: 
          { return Parser.THIS;
          }
        case 43: break;
        case 19: 
          { return Parser.LEN;
          }
        case 44: break;
        case 23: 
          { return Parser.RETURN;
          }
        case 45: break;
        case 15: 
          { return Parser.ELSE;
          }
        case 46: break;
        case 13: 
          { return Parser.VOID;
          }
        case 47: break;
        case 17: 
          { return Parser.FALSE;
          }
        case 48: break;
        case 11: 
          { return Parser.TRUE;
          }
        case 49: break;
        case 3: 
          { return Parser.Identifier;
          }
        case 50: break;
        case 10: 
          { return Parser.NEW;
          }
        case 51: break;
        case 18: 
          { return Parser.WHILE;
          }
        case 52: break;
        case 5: 
          { return Parser.INTEGER_LITERAL;
          }
        case 53: break;
        case 9: 
          { return Parser.INT;
          }
        case 54: break;
        case 1: 
          { System.err.println("Error: unexpected character '"+yytext()+"' na linha "+yyline); return YYEOF;
          }
        case 55: break;
        case 6: 
          { 
          }
        case 56: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              { return 0; }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
